version: "3"

volumes:
  redis_data:
    driver: local

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: msgeo_app
    volumes:
      - .:/home/node/app
    ports:
      - "8081:8080"

  redis:
    image: redis:6.0
    container_name: msgeo_redis
    command: --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "25555:6379"
